swagger: '2.0'
info:
  title: Bank Argent API Transactions documentation
  description: This API documentation outlines the endpoints for the Transaction functionality of Bank Argent's banking system
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get All User Accounts
      description: API for retrieving all accounts of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          
  /transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get All Transactions for an Account
      description: API for retrieving all transactions of a specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: ID of the account
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
          
  /transactions/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get One Transaction
      description: API for retrieving details of a specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: ID of the account
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
          
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction
      description: API for updating transaction information (add, modify, delete)
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: ID of the account
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction information
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
        
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header  

definitions:

  Account:
    type: object
    properties:
      id:
        type: string
        description: Account identifier
      title:
        type: string
        description: Account title
      numAccount:
        type: string
        description: Account number
      amount:
        type: number
        format: double
        description: Current account balance
      description:
        type: string
        description: Account description

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction identifier
      date:
        type: string
        format: date-time
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        format: double
        description: Transaction amount
      balance:
        type: number
        format: double
        description: Account balance after transaction
      type:
        type: string
        description: Transaction type (e.g., Electronic, Manual)
      category:
        type: string
        description: Transaction category
      notes:
        type: string
        description: User notes about the transaction

  TransactionUpdate:
    type: object
    properties:
      description:
        type: string
        description: Updated transaction description
      category:
        type: string
        description: Updated transaction category
      notes:
        type: string
        description: Updated user notes about the transaction
          